### ISSUE TITLE
互Star链接点击后会返回主页

### ISSUE THREAD

**Issue by Cubik65536** [GitStar666/GitHubStar#17]
在点击相互Star的链接之后，该链接会被重定向至主页且登陆失效
浏览器：macOS Safari Version 14.0.3 (16610.4.3.1.7)

**Comment by Cubik65536** [comment]
Chrome并无相关问题

**Comment by giswangsj** [comment]
这个应该和浏览器没有关系，因为有很多用mac的用户。可能是个别的仓库出了问题，点赞时返回异常，你再确认一下，如果仓库有问题，可以在点赞界面右上角上报该仓库
