### ISSUE TITLE
贊助網站

### ISSUE THREAD

**Issue by tsung-wei-huang** [GitStar666/GitHubStar#18]
請問支援paypal嗎？人在國外無法用wechat pay

**Comment by giswangsj** [comment]
不好意思，暂不支持

**Comment by tsung-wei-huang** [comment]
有沒有啥辦法能讓我開通點讚權限（帳戶296) ，目前無法使用wechat pay，人在美國 :(

很謝謝你設計這個網站！

**Comment by giswangsj** [comment]
已经帮你临时打开了，不过一段时间后系统还是会自动收回权限的

**Comment by tsung-wei-huang** [comment]
太感謝了！如果能夠支援用Paypal就更好了 :)
